export interface anexo1{
  numeroCaso: string,
  Unidad_Ejecutora: string,
  isToday: string,
  fecha_hora_recepcion: Date,
  hora_recepcion: string,
  lugar: string,
  recibido_por:string,
  medios_recepcion: string,
  carta_Recepcion:string,
  nombre: string,
  apellido: string,
  ciudad: string,
  correoT: string,
  otro: string,
  tipo_Caso: string,
  detalle: string,
  docu: File | null,
  lugar_caso: string,
  fecha_caso: string,
  Obv_Ads: string,
  NombreResponsable: string,
  cargo: string
}