export interface anexo5 {
  nombre: string,
  numeroCaso: string,
  Unidad_Ejecutora: string,
  subproyecto: string,
  conprosub: string,
  encargado: string,
  fecha_hora_incidente: string,
  lugar: string,
  fecha_hora_recepcion: string,
  medios_Recepcion:string,
  recepcion_Escrita:string,
  confidencial_Concentimiento:string,
  quien_Reporta: string,
  otro: string,
  especifique: string,
  org: string,
  contratista: string,
  subcontratista: string,
  proveedor: string,
  tipo_Reporte: string,
  detalle: string,
  documento: File | null, //los inputs de documentos se tratan de manera diferente
  fecha_caso: string,
  genero_sobreviviente: string,
  edad_sobreviviente: string,
  relacion_sobreviviente: string,
  genero_agresor: string,
  edad_agresor: string,
  relacion_agresor: string,
  adicional: string,
  nombreresponsable: string,
  cargoresonsable: string,
  lugar_caso: string
}